database:
  adapter:  mysql2
  host:     127.0.0.1
  port:     3306
  username: root
  password: ''
  database: pick_development
  url:

logger:
  output:       stdout  # Available output is stdout.
  formatter:    text    # Available formatters are: text(default) and json.
  level:        info    # Available log levels are trace, debug, info(default), warn, error, fatal, panic.
