version: "3"
services:
  pick:
    image: syaroslav/pick:0.0.sk
    ports:
    - "8080:8080"
    environment:
    - "PICK_SERVER_ADDR=:8080"
    - "PICK_GZIP=true"
    - "PICK_DEBUG=true"
    - "PICK_DATABASE_DRIVER=mysql"
    - "PICK_DATABASE_NAME=pick"
    - "PICK_DATABASE_USER=pick"
    - "PICK_DATABASE_PASSWORD=changeme"
    - "PICK_DATABASE_HOST=mysql:3306"
    - "PICK_SECRET=GMWJGSAPGATLMODYLUMGUQDIWWMNPPQIMGEGMGKB"
    links:
    - "mysql:mysql"
    depends_on:
    - mysql
    restart: always
    command: ./pick server
  mysql:
    image: "mysql:5"
    volumes:
    - ./mysql-data:/var/lib/mysql
    ports:
    - "127.0.0.1:3306:3306"
    environment:
    - "MYSQL_ALLOW_EMPTY_PASSWORD=false"
    - "MYSQL_DATABASE=pick"
    - "MYSQL_PASSWORD=changeme"
    - "MYSQL_ROOT_PASSWORD=changeme"
    - "MYSQL_USER=pick"
    restart: always
