version: "3"
services:
  pick:
    image: syaroslav/pick:latest
    ports:
    - "8080:8080"
#    environment:
    links:
    - "mysql:mysql"
    depends_on:
    - mysql
    restart: always
  mysql:
    image: "mysql:5"
    volumes:
    - ./mysql-data:/var/lib/mysql
    ports:
    - "127.0.0.1:3306:3306"
    environment:
    - "MYSQL_ALLOW_EMPTY_PASSWORD=false"
    - "MYSQL_DATABASE=pick"
    - "MYSQL_PASSWORD=password01"
    - "MYSQL_ROOT_PASSWORD=password01"
    - "MYSQL_USER=pick"
    restart: always
